#!/usr/bin/env bash
# Build the standalone `swr` binary — the install path that needs no clone to
# stay on disk and no path from the binary to the skill text.
#
#   tools/build.sh                 # → ./dist/swr for this machine
#   SWR_OUT=/usr/local/bin/swr tools/build.sh
#   tools/build.sh --install       # build, then install into $SWR_BIN_DIR (~/.local/bin)
#
# bun is a build-time dependency only (`brew install oven-sh/bun/bun`). It
# compiles tools/swr plus the skill text into one executable, so `swr init`
# works from ~/.local/bin with no repository anywhere on the machine.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${SWR_BIN_DIR:-$HOME/.local/bin}"
INSTALL=0
[ "${1:-}" = "--install" ] && INSTALL=1

command -v bun >/dev/null 2>&1 || {
  echo "ERROR: bun is required to build (brew install oven-sh/bun/bun)"; exit 1; }
SKILL="$REPO_DIR/skills/smart-web-read/SKILL.md"
[ -f "$SKILL" ] || { echo "ERROR: missing $SKILL"; exit 1; }

OUT="${SWR_OUT:-$REPO_DIR/dist/swr}"
mkdir -p "$(dirname "$OUT")"

# Work in a temp copy of the tree: the generated embed module must never land in
# the checkout, where it would freeze a stale copy of the skill into the source.
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
cp -R "$REPO_DIR/tools" "$TMP/tools"
cp "$REPO_DIR/package.json" "$TMP/package.json"
cp -R "$REPO_DIR/skills" "$TMP/skills"

# bun treats an extensionless entry point as an asset: it compiles a binary that
# prints nothing and exits 0. Build from a `.js` copy so the file is parsed as
# the program it is.
ENTRY="$TMP/tools/swr.js"
cp "$REPO_DIR/tools/swr" "$ENTRY"

{
  printf '#!/usr/bin/env node\n'
  printf "'use strict';\n"
  printf '/* Generated by tools/build.sh — do not edit. The skill text rides inside the\n'
  printf ' * binary so `swr init` works with no repository beside it. */\n'
  # One literal, not a folded list: adjacent strings are separate arguments to
  # Buffer.from, and the second one is then read as the encoding.
  printf "const EMBEDDED_SKILL_MD = Buffer.from('%s', 'base64').toString('utf8');\n" \
    "$(base64 < "$SKILL" | tr -d '\n')"
  printf 'module.exports = { EMBEDDED_SKILL_MD };\n'
} > "$TMP/tools/skill-embed.js"

echo "build: bun $(bun --version) → $OUT"
(cd "$TMP" && bun build --compile --target=bun --outfile "$OUT" tools/swr.js >/dev/null)
chmod +x "$OUT"

# Prove it stands alone — run it from a directory with no tree around to read —
# and that it is this program: the empty binary above also exited 0, so an exit
# code on its own would report success for a build that deploys nothing.
STANDALONE="$(cd "$(mktemp -d)" && "$OUT" --version)"
case "$STANDALONE" in
  "swr "*) ;;
  *) echo "ERROR: built binary did not answer --version (got: ${STANDALONE:-<no output>})"; exit 1;;
esac

if [ "$INSTALL" -eq 1 ]; then
  mkdir -p "$BIN_DIR"
  install -m 755 "$OUT" "$BIN_DIR/swr"
  echo "installed: $BIN_DIR/swr (real binary, not a symlink into a clone)"
  case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "WARNING: $BIN_DIR is not in PATH — add it to your shell profile";;
  esac
  echo "next: swr init   # deploy the embedded skill into every agent root"
fi
